### ISSUE TITLE
0.12

### ISSUE THREAD

**Issue by 19h** [Level/level-lmdb#1]
I kindly request some love for this module.. it's lonely and cries every time I want to install it.

:walking:

**Comment by dominictarr** [comment]
if you see a job that needs doing that is your job ;)

**Comment by 19h** [comment]
Well, that's significantly true. I have no idea about NaN, though. 😒

**Comment by dominictarr** [comment]
@rvagg loves to see new people become C++ programmers, so I'm sure he'll be happy to give you pointers if necessary!

**Comment by rvagg** [comment]
well then, let me recommend [goingnative](https://github.com/rvagg/goingnative) to you!

**Comment by 19h** [comment]
If there was a way to do native in C.. :smirk: good job with the tutorial, though!

**Comment by vweevers** [comment]
This project is likely to be archived (https://github.com/Level/community/issues/29). While we do intend to bring it to a reasonably up-to-date state beforehand, node 0.12 is old, so I'm closing this ticket.
