### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-lmdb#12]
- [x] Disable Greenkeeper
- [x] Make sure the latest published version is git-tagged
- [x] Add note to readme (example: https://github.com/Level/level-mobile/pull/22)
- [x] Remove project from Travis
- [x] Pin dependencies
- [x] Ask for npm ownership
- [x] Release a final patch version
- [x] Deprecate the package with `This project has been abandoned. There will be no further releases. If you wish to revive level-lmdb, please open an issue (https://github.com/Level/community) to discuss a way forward. Thank you!`
- [x] ~~Remove extraneous npm owners~~
- [x] Archive the GitHub repository

**Comment by vweevers** [comment]
@rvagg Would you mind running `npm owner add vweevers level-lmdb`? Thanks!

**Comment by rvagg** [comment]
👍 done
